services:
  server:
    container_name: caddy-server
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/caddy:ro
      - /docker/caddy/data:/data:rw
      - /docker/caddy/config:/config:rw
    environment:
      DOMAIN: ${DOMAIN}
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_API_SECRET_KEY: ${PORKBUN_API_SECRET_KEY}

networks:
  default:
    name: gateway_network
