services:
  server:
    container_name: npm-server
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /docker/npm/app:/data:rw
      - /letsencrypt:/etc/letsencrypt:rw
    environment:
      TZ: ${TZ}
      DB_POSTGRES_HOST: postgres
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: ${POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: npm-database
    image: postgres
    restart: unless-stopped
    volumes:
      - /docker/npm/database:/var/lib/postgresql:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}'"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

networks:
  default:
    name: gateway_network